---
- name: Setup nethermind service
  block:
    - name: Create nethermind service file
      template:
        src: nethermind.service.j2
        dest: /etc/systemd/system/{{ service.servicename_execution_client }}.service
        mode: '0644'

    - name: Reload systemd to recognize the new service
      command: systemctl daemon-reload
      become: true

    - name: Enable the service to start on boot
      systemd:
        name: "{{ service.servicename_execution_client }}"
        enabled: yes

    - name: Start the service
      systemd:
        name: "{{ service.servicename_execution_client }}"
        state: started


- name: Setup nimbus service
  block:
    - name: Create nimbus service file
      template:
        src: nimbus_bn.service.j2
        dest: /etc/systemd/system/{{ service.servicename_beacon_client }}.service
        mode: '0644'

    - name: Reload systemd to recognize the new service
      command: systemctl daemon-reload
      become: true

    - name: Enable the service to start on boot
      systemd:
        name: "{{ service.servicename_beacon_client }}"
        enabled: yes

    - name: Start the service
      systemd:
        name: "{{ service.servicename_beacon_client }}"
        state: started