---
- name: Setup Node
  hosts: all
  become: true

  tasks:
    - name: Install dependencies
      include_role:
        name: roles/install_dependencies
        apply:
          tags: always
      tags:
        - dependencies

    - name: Setup jwt
      include_role:
        name: roles/setup_jwt
        apply:
          tags: always
      tags:
        - jwt

    - name: Install nethermind 
      include_role:
        name: roles/install_nethermind
        apply:
          tags: always
      tags:
        - install
        - nethermind

    - name: Install nimbus
      include_role:
        name: roles/install_nimbus
        apply:
          tags: always
      tags:
        - install
        - nimbus
